"""First migrtaion

Revision ID: 0629dae783a4
Revises: 98b89d30a79d
Create Date: 2024-06-16 22:42:58.506880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0629dae783a4'
down_revision = '98b89d30a79d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
